### ISSUE TITLE
AppVeyor Build Fails

### ISSUE THREAD

**Issue by dswah** [conda-forge/pygam-feedstock#7]
Issue:
**AppVeyor CI build fails**

https://ci.appveyor.com/project/conda-forge/pygam-feedstock-rabgb/builds/19886325
https://github.com/conda-forge/pygam-feedstock/branches

CircleCI passes each time, but AppVeyor Fails.

<br/>
Details About Build Error
<details>

```
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.
```
</details>

@bgruening does this need a re-render like you suggested?

**Comment by xhochy** [comment]
We no longer use AppVeyor.
